"""empty message

Revision ID: 0d9892a4d36c
Revises: 974c17a5c9d0
Create Date: 2022-07-27 18:33:19.033381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9892a4d36c'
down_revision = '974c17a5c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('name_owner_fkey', 'name', type_='foreignkey')
    op.drop_column('name', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('name', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('name_owner_fkey', 'name', 'users', ['owner'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
