"""empty message

Revision ID: 974c17a5c9d0
Revises: 4c682e22f608
Create Date: 2022-07-27 16:03:15.861488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974c17a5c9d0'
down_revision = '4c682e22f608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('name', sa.Column('owner', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'name', 'users', ['owner'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'name', type_='foreignkey')
    op.drop_column('name', 'owner')
    # ### end Alembic commands ###
